### ISSUE TITLE
Request of commit access for repo maintenance

### ISSUE THREAD

**Issue by pfalcon** [Linaro/lite-lava#4]
@galak, recently @vanti asked about the situation with this repo, and the only logical answer was that this repo isn't really being updated to upstream, i.e. not really maintained. However, recently I find more and more issues with LAVA, which affect/would affect testing of our device class (i.e. MCU-based devices), and fixes for which aren't exactly obvious (require long back-and-forth with upstream, or just being picked up by upstream maintainers).

So, who knows, we might need to maintain a branch with a workarounds/WIP fixes again. So, I'd like to request commit access similar to the https://github.com/Linaro/lite-lava-docker-compose/ repo, to at least regularly pull upstream changes into the "master" branch, and rebase "lite" branch to it. Any further changes will be of course subject to individual reviews and discussions.

**Comment by galak** [comment]
@pfalcon I've added you as a collaborator which should in theory give you commit access.

I'm good with you taking over this repo.

**Comment by galak** [comment]
I noticed we now have what seems like a mirror or the lava gitlab repo on github...  https://github.com/Linaro/lava

**Comment by pfalcon** [comment]
@galak, Thanks, confirming that everything works as expected. I've synced master branch with upstream, and rebased "lite" on the 2019.11 tag (because master no longer works with our "devel" setup, as mentioned in https://github.com/Linaro/lite-lava-docker-compose/pull/36#issuecomment-560963652). Will do such updated from time to time.
